import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ToastProvider } from "@/components/ui/toast";
import { Toaster } from "@/components/ui/toaster";
import { ClerkProvider } from "@clerk/nextjs";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider appearance={{
      
    }}>
      <html lang="en">
        <body className={inter.className}>
          <ToastProvider>
            {children}
            <Toaster /> {/* Removed unsupported props */}
          </ToastProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
